---
kind: pipeline
name: "Build not on master"

steps:
- name: node
  image: node
  commands:
  - npm install
  - npm run build
  when:
    branch:
      exclude:
      - master

- name: docker  
  image: plugins/docker
  settings:
    username:
      from_secret: registry_username
    password:
      from_secret: registry_password
    repo: javanya/next-docker
    tags: ${DRONE_COMMIT_SHA:0:7}